# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    firewalls:
        administration:
            switch_user: true
            context:     user
            pattern:     /administration/.*
            form_login:
                provider:     fos_userbundle
                login_path:   fos_user_security_login
                check_path:   fos_user_security_check
                failure_path: fos_user_security_login
                default_target_path: sylius_backend_dashboard
                use_forward:  false
                use_referer:  true
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            anonymous: true

        main:
            switch_user: { role: ROLE_SYLIUS_ADMIN }
            context:     user
            pattern:     /.*
            form_login:
                provider: fos_userbundle
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                failure_path: fos_user_security_login              
                default_target_path: sylius_backend_dashboard
                use_forward:  false
                use_referer: true
            remember_me:
                key: %sylius.secret%
                name: APP_REMEMBER_ME
                lifetime: 31536000
                always_remember_me: true
                remember_me_parameter: _remember_me
            oauth:
                resource_owners:
                    amazon:   "/login/check-amazon"
                    facebook: "/login/check-facebook"
                    google:   "/login/check-google"
                login_path:   /connect
                failure_path: /connect
                oauth_user_provider:
                    service: sylius.oauth.user_provider
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
        
            anonymous: true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: "/login.*", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/connect.*", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/register", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/resetting", role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: "/administration/login", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration/login-check", role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: "/administration.*", role: ROLE_SYLIUS_ADMIN }

        - { path: "/account.*", role: ROLE_USER }
        - { path: "/account.*", role: ROLE_SYLIUS_ADMIN }

        - { path: "/_partial.*", ip: 127.0.0.1 }
